# https://starship.rs/config/

prompt_order = [
  "time",
  "custom",
  "username",
  "hostname",
  "kubernetes",
  "directory",
  "git_branch",
  "git_commit",
  "git_state",
  "git_status",
  "hg_branch",
  "docker_context",
  "package",
  "dotnet",
  "elixir",
  "elm",
  "erlang",
  "golang",
  "java",
  "julia",
  "nim",
  "nodejs",
  "ocaml",
  "php",
  "purescript",
  "python",
  "ruby",
  "rust",
  "terraform",
  "zig",
  "nix_shell",
  "conda",
  "memory_usage",
  "aws",
  "env_var",
  "crystal",
  "cmd_duration",
  "line_break",
  "jobs",
  "battery",
  "character",
]

[aws]
symbol = "îŒ½ "
# yellow
style = "bold 136"

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

  # "bold red" style when capacity is between 0% and 10%
  [[battery.display]]
  threshold = 10
  style = "bold 124"

  # "bold yellow" style when capacity is between 10% and 30%
  [[battery.display]]
  threshold = 30
  style = "bold 136"

[character]
# Replace the "â¯" symbol in the prompt with "âœ"
symbol = "â™ "
# Change the symbol & its color
use_symbol_for_status = true
# black
style_success = "bold 0"
# red
style_failure = "bold 124"

[directory]
# bold green
style = "bold 64"

[docker]
symbol = "ïŒˆ "

# [env_var]
# variable = "VAULT_ADDR"

[git_branch]
# bold violet
style = "bold 61"
symbol = "ï˜ "

[git_state]
cherry_pick = "ğŸ’ PICKING"
# bold yellow
style = "bold 136"

[git_status]
# Show ahead/behind count of the branch being tracked
show_sync_count = true
# default, bold blue
style = "bold 33"
# cyan
conflicted.style = "37"
# black
deleted.style = "0"
# red
modified.style = "124"
# default
# renamed.style = ""
# green
staged.style = "64"
# yellow
stashed.style = "136"
# orange
untracked.style = "166"

[golang]
symbol = "î˜§ "

[hostname]
ssh_only = true
# yellow
# style = "bold dimmed 136"
# red
style = "bold 124"

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[memory_usage]
symbol = "ï¡š "

[nodejs]
symbol = "î‰ "

[package]
symbol = "ï£– "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "ï€“ "

[terraform]
# This is very slow currently, so it is disabled by default
# show_version = true

[time]
disabled = false
format = "ğŸ•™ %T"

[username]
show_always = true
# bold orange
style_user = "bold 166"
